# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f627d673f244c49da992a85b74436fcc1a80b72bd608b4170c28a908d536bf78368d136a941c98ecd0f8781bdaeb1bc5fe413131c44a06cbd2a921c89a7d7e3

test:
  secret_key_base: d7f6a9e87bff50eceefce3ffe13385b756364c74e2daf667d3b1a0585c85f8ac9d3c12aa4b959b307dd4f9b80bc46b44132a3f78bae935c5454b17c639f654a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
